### ISSUE TITLE
Role of kafka

### ISSUE THREAD

**Issue by zurrehma** [ligato/vpp-agent#1306]
Can somebody will tell me about role of Kafka in this whole processes?

**Comment by VladoLavor** [comment]
Hello @zurrehma 

As you probably know, Kafka is a messaging service which allows you to stream or **produce** data to Kafka server from a process, and use the same or different process to listen or **consume** those messages. And also that messages are ordered using offset number and sorted into topics and partitions.

The Ligato VPP-Agent provides a messaging [plugin](https://github.com/ligato/cn-infra/tree/master/messaging/kafka) which allows you to create producers/consumers able to send Kafka messages synchronously or asynchronously. 

You can read more about it in our [Kafka documentation](http://docs.ligato.io/en/latest/plugins/infra-plugins/#messagingkafka) and try the example with Kafka as the library [here](https://github.com/ligato/cn-infra/tree/master/examples/kafka-lib) or as the plugin with [hash partitioner](https://github.com/ligato/cn-infra/tree/master/examples/kafka-plugin/hash-partitioner), [manual partitioner](https://github.com/ligato/cn-infra/tree/master/examples/kafka-plugin/manual-partitioner) and also how to start [post-init consumer](https://github.com/ligato/cn-infra/tree/master/examples/kafka-plugin/post-init-consumer).

The Ligato image with VPP-Agent version < 2.0.0 implicitly requires Kafka to run since the startup configuration was automatically provided even if the user does not need it (it was because of some legacy reasons where previously the VPP-Agent could not be started without Kafka). The version 2.0.0 removed this requirement and Kafka is now purely optional and it depends on you whether you need it or not.

**Comment by ondrej-fabry** [comment]
Closing due age.
