### ISSUE TITLE
Mounting host directory in Docker container returns: operation not permitted

### ISSUE THREAD

**Issue by munnawar4699** [ligato/vpp-agent#789]
ERRO[0000] mount --make-shared failed                    loc="nsplugin/namespaces.go(222)" logger=linux-plugin-ns-handler namespace=veth-cfg-ns
ERRO[0000] plugin Linux: Init failed: operation not permitted  loc="core/agent_core.go(264)" logger=agentcore took="488.906µs"

**Comment by ondrej-fabry** [comment]
You need to use `--privileged` flag for `docker run` command to give extended privileges to the container.

**Comment by ondrej-fabry** [comment]
This needs to be documented better as it's currently only mentioned in [docker/dev/README.md](https://github.com/ligato/vpp-agent/blob/master/docker/dev/README.md#starting-the-image), which does not seem to be enough, because it's being encountered by new users repeatedly.

Perhaps the warning/error message could include hint that the privileged mode should be enabled.

**Comment by VladoLavor** [comment]
At this point, I think it is documented well since it's mentioned in several places which are more available than the mentioned readme file, since everything is on the wiki page:
- [Linux interface plugin limitations](https://github.com/ligato/vpp-agent/wiki/Linux-Interface-plugin#limitations)
- [How-to-guide in the "starting the image" part](https://github.com/ligato/vpp-agent/wiki/Learn-how-to#start-the-image)
- [Quickstart guide](https://github.com/ligato/vpp-agent/wiki/Quickstart#5-start-the-vpp-agent)
- [FAQ](https://github.com/ligato/vpp-agent/wiki/FAQ#the-vpp-agent-failed-to-start-with-the-message-mount---make-shared-failed-permission-denied)

(Please note that the links above may not work after some time since the wiki is changing frequently)
