### ISSUE TITLE
Walkthough of using the agent

### ISSUE THREAD

**Issue by iawells** [ligato/vpp-agent#995]
For the purposes of introducing people to both cn-infra and the vpp-agent, we need a training document - kept within the repository and current with the code version - that explains how you would write an agent with intelligence in it and the benefits of using Ligato components to do so.  This needs to be at the level of explaining to someone who understands SDN, and has found the VPP API documentation at fd.io, how they might create a simple agent that controls VPP for SDN purposes.

**Comment by mestery** [comment]
This is a really good idea, and it should definitely be checked into the repository. Showing how to use this to build CNFs, in the context of someone who understands SDN, is a great idea.

**Comment by ondrej-fabry** [comment]
The vpp-agent repository desperately needs documentation update. There have already been several people asking about the required steps for extending the agent. And at the moment Mahesh and co. is also at a stage where such documentation would be really helpful.

However, we are currently in the process of *heavy refactoring* (see [dev branch](https://github.com/ligato/vpp-agent/tree/dev)) of the core logic which connects NB (proto models) with SB (VPP API), which we call **KVScheduler**. Currently the implementation is 90% done, we are in the process of cleaning up some remaining parts and then we plan to focus on testing. If all goes OK (actually it's going pretty good so far) then we will switch to dev branch as main development branch and we will deprecated the old v1 version.

For this reason I would probably rather do the documentation for the new KVScheduler instead of creating docs for the soon to be deprecated way to do things.

@milanlenco thoughts?

**Comment by milanlenco** [comment]
I agree, I definitely plan to contribute with a developer guide for KVScheduler when I'm done with the current set of tasks planned for Contiv (lighter refactoring in there).

**Comment by jmedved** [comment]
+1. But let's put an ETA for when new documentation would be available. Also, when you guys start on it, so that we can give ongoing feedback.

**Comment by iawells** [comment]
Please note: 'developer guide' can mean a lot of things to different people so I'm going to add a clarification of why I asked for what I did.  I want to see a means to actually enable people to use Ligato.  This would, I think, have to begin with a worked example - here's a problem, to solve it here's what you do and why you do it that way - before going to the nitty 'here are all the APIs' level - which just leaves a dev in a twisty maze of APIs and no clues which ones to use for what (plus a good chance that they will reinvent something in the Ligato framework because they didn't know it was there).  We need the API/component documentation *as well*, but that's not enough by itself.

**Comment by ondrej-fabry** [comment]
Our new Ligato documentation site should provide more information: https://docs.ligato.io/

If you encounter some problems or missing parts please report as new issue.
